/**
 * [상수] worker/src/errorCodes.ts
 * 설명:
 *   - 워커와 Native Helper에서 사용하는 오류 코드를 전역 상수로 정의한다.
 * 버전: v0.6.0
 * 관련 설계문서:
 *   - design/contracts/v0.6.0-portfolio-media-contract.md
 */
export const ERROR_CODES = {
  FFPROBE_INVALID_OUTPUT: 'FFPROBE_INVALID_OUTPUT',
  FFMPEG_TIMEOUT: 'FFMPEG_TIMEOUT',
  FFMPEG_EXIT_NONZERO: 'FFMPEG_EXIT_NONZERO',
  FFMPEG_ENCODE_ERROR: 'FFMPEG_ENCODE_ERROR',
  EXPORT_TRIVIAL_FRAMES: 'EXPORT_TRIVIAL_FRAMES',
  FAILED_NATIVE_VALIDATION: 'FAILED_NATIVE_VALIDATION',
  OUTPUT_ATOMIC_MOVE_FAILED: 'OUTPUT_ATOMIC_MOVE_FAILED',
  HWACCEL_UNAVAILABLE: 'HWACCEL_UNAVAILABLE',
  HWACCEL_HANDSHAKE_FAILED: 'HWACCEL_HANDSHAKE_FAILED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const
